language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '5'
before_script:
  - npm prune
script:
  - npm test
after_success:
  - npm run semantic-release -- pre
  - npm run clean
  - npm run build
  - npm publish
  - npm run semantic-release -- post
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
